// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Product struct {
	ID          int64
	Name        string
	Description string
	Stock       int32
	Price       float64
}

type User struct {
	ID       int64
	Username string
	Password string
}
